# Generated by Django 4.2 on 2025-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0003_alter_detallepedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='usuario',
        ),
        migrations.AddField(
            model_name='resena',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
