# Generated by Django 4.2 on 2025-06-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0004_remove_resena_usuario_resena_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='resena',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')]),
        ),
    ]
